[shaker]
model = "DYN-PM-10"
manufacturer = "Dynalabs"
nominal_force = 10.0 # [N] Nominal force
manual = "DYN_PM-10_PRODUCT_MANUAL.pdf"

[limits]
force = 10.0 # [N] Output force limit
displacement_pk_pk = 4.0 # [mm] Displacement limit (peak-to-peak)
acceleration_sine = 490.5 # [m/s^2] Acceleration limit (sine), [50 g converted to m/s^2]

[performance]
frequency_range = [10.0, 10000.0] # [Hz] Frequency range
payload_capacity = 0.0 # [kg] Zero Payload capacity (modal shaker - used with stinger)
max_input_current = 4.0 # [A] RMS Maximum input current
max_input_voltage = 1.0 # [Vac] Maximum peak input voltage
operating_temperature_range = [5.0, 35.0] # [Â°C] Operating temperature range

[dimensions]
moving_mas = 0.02 # [kg] Moving mass
shaker_mass = 1.3 # [kg] Shaker mass
amplifier_mass = 0.65 # [kg] Accompanying external amplifier mass
